### ISSUE TITLE
Unclear documentation: pagination is URL segment instead of param

### ISSUE THREAD

**Issue by StevenLangbroek** [backbone-paginator/backbone.paginator#216]
I'm developing a front-end over a CodeIgniter-based API, which uses `posts/P:offset` (ie /posts/P10) for pagination. I'm unsure based on the docs how I would handle this, as all I can find is how to set the params.. Can someone maybe shed some light on this?

**Comment by n0nick** [comment]
Documentation still doesn't cover that, but from [the source](https://github.com/backbone-paginator/backbone.paginator/blob/9b46e52/lib/backbone.paginator.js#L1132) I gathered that the `url` parameter can be used as a function, so @StevenLangbroek's use-case can be worked out as:

```javascript
url: function() {
  return '/posts/P:offset'.replace(':offset', 10);
}
```
