### ISSUE TITLE
Issue when the last page is being empty

### ISSUE THREAD

**Issue by AndrewEastwood** [backbone-paginator/backbone.paginator#250]
Hi there!

I have the the list where one column has select cells with the following options [active, closed]
And there are also two lists, which are displayed in the corresponding tabs.
So when I'm on the Active tab all records are displayed with active state only, and when I change any record and set state = "closed" the record is being moved to the list for closed records.
The problem is when I have more then 1 pages and only one record on the last page, and then when I change its status to another it crashes with the error message:
```Uncaught RangeError: `currentPage` must be firstPage <= currentPage > totalPages if 1-based. Got 2.```
I looked into the source and saw the moment when the condition validates current page with available pages. In my case I am still on the second page but it's no longer exists, because I removed the last record within it.
What do you think about changing the condition and do smth like this:
```
        if (mode == "infinite") {
          if (!links[currentPage + '']) {
            throw new RangeError("No link found for page " + currentPage);
          }
        } // here we adjust current page
        else if (currentPage > totalPages) {
          currentPage = state.currentPage = totalPages;
        }
        else if (currentPage < firstPage) {
          throw new RangeError("`currentPage` must be firstPage <= currentPage " +
                               (firstPage ? ">" : ">=") +
                               " totalPages if " + firstPage + "-based. Got " +
                               currentPage + '.');
        }
```
https://github.com/backbone-paginator/backbone.paginator/blob/master/lib/backbone.paginator.js#L594

**Comment by qferr** [comment]
@wyuenho ping

**Comment by wyuenho** [comment]
On this now
