### ISSUE TITLE
Cannot assign to read only property error in Chrome 38+ and Safari 6+

### ISSUE THREAD

**Issue by BarFoo** [backbone-paginator/backbone.paginator#259]
When using the data attribute of a pageable collection's fetch using jQuery.param Chrome v38 and Safari 6 both throw a cannot assign to read only property error.

Example code:

    var myCollection = new MyCollection(); // Some pageable collection

    var params = {
        'someFilter': 'someFilterVal'
    };

    myCollection.fetch({
        data: $.param(params), // When using this form of applying custom filters.
        success: mySuccessFunction
    });

This was working fine before in Safari 5 and Chrome < 38.

The line of code in Backbone.Paginator where this error occurs is within the conditional statement starting line 1152:

    if (state[k] != null && v != null) {
       data[v] = state[k];
    }

**Comment by wyuenho** [comment]
`data` is expected to be a JS object. You cannot supply a string because both backbone and backbone.paginator expect a JS object.
