### ISSUE TITLE
Error installing from NPM

### ISSUE THREAD

**Issue by forddyce** [backbone-paginator/backbone.paginator#260]
I got this everytime running `sudo npm install backbone.paginator`:

> 629 error peerinvalid The package handlebars does not satisfy its siblings' peerDependencies requirements!
630 error System Linux 3.13.0-38-generic
631 error command "/usr/bin/node" "/usr/bin/npm" "install" "backbone.paginator"
632 error cwd /home/ford/web/www-suberbo
633 error node -v v0.10.32
634 error npm -v 1.4.28
635 error code EPEERINVALID
636 verbose exit [ 1, true ]

Any solution?

**Comment by wyuenho** [comment]
Most likely a network issue. Please reopen if this is still an issue.
