### ISSUE TITLE
reset method( Collection.reset() ) does not reset the totalRecords state to fullCollection.length

### ISSUE THREAD

**Issue by shreyasubale** [backbone-paginator/backbone.paginator#265]
If i have a already populated collection, and then reset it, then the resulting collection's state (totalrecords , pages ) does not reflect the new changes.

**Comment by wyuenho** [comment]
See https://github.com/backbone-paginator/backbone.paginator/issues/293#issuecomment-145112814

**Comment by sirianni** [comment]
The comment for #293 does not make sense in this context.  That bug was asking for the pagination state to be changed, this is asking for the `totalRecords` count to be changed.  The latter is legitimate.  Without changing the `totalRecords` count the `hasNextPage()` and other methods are incorrect.

**Comment by sirianni** [comment]
A common pattern in Backbone apps is to reset a collection vs. re-instantiating it.  This allows all the upfront wiring of that collection to views to continue to function properly without losing the reference.  Without being belt to use `reset` properly on `PageableCollection`, this severely constrains the usage.

**Comment by wyuenho** [comment]
@sirianni are you talking about resetting just the page or the entire collection (i.e. `fullCollection`) ?

**Comment by sirianni** [comment]
The `fullCollection`.  I have been doing that by calling `reset` on the `PageableCollection` wrapper.  Should I be doing reset on `collection.fullCollection` directly?

**Comment by wyuenho** [comment]
Yes. That'll work.
