### ISSUE TITLE
collection.fullCollection only contains latest models after I getNextPage()

### ISSUE THREAD

**Issue by theirishpenguin** [backbone-paginator/backbone.paginator#267]
Using backbone 1.0.0 with backbone paginator 2.0.2. Is there any reason that this configuration should be leading to this issue? I am trying to eliminate that it's not something on my side. Not matter how often I call getNextPage() the collection.fullCollection only contains 25 models (which is my page size).

Is there any common gotcha that could be causing this to happen? I've tried lots of variants on getNextPage(), getNextPage({reset: false}), getNextPage({reset: false, add: false, remove: false}) but to no avail.

**Comment by wyuenho** [comment]
Backbone 1.0.0 has broken a number of things. It's not supported by backbone.paginator. Please upgrade backbone to 1.1.2
