### ISSUE TITLE
Problems with loading Backbone.Paginator in Browserify latest

### ISSUE THREAD

**Issue by baer** [backbone-paginator/backbone.paginator#277]
After a clean install of my app on a new machine (npm install the latest libs) I've found I'm no longer able to load Backbone.Paginator correctly. I ran a diff of my newly installed backbone.paginator (same tag in package.json) and the one I have in production and I see the following difference:

```
  // CommonJS
  if (typeof exports == "object") {
    module.exports = factory((typeof window !== "undefined" ? window._ : typeof global !== "undefined" ? global._ : null), (typeof window !== "undefined" ? window.Backbone : typeof global !== "undefined" ? global.Backbone : null));
  }
```

The new one I just pulled shows this:
```
  // CommonJS
  if (typeof exports == "object") {
    module.exports = factory(require("underscore"), require("backbone"));
  }
```

I've been loading this in my app code using the following:
```
// Plugins
require('../../../node_modules/backbone.paginator/lib/backbone.paginator.js');
```
I'm not sure how exactly that would cause a problem but it does not attach correctly to the Backbone object anymore. The only way I've gotten around this is to force the library into browser mode by editing the source which is obviously not a long term solution. Do you have any idea how the code would have changed from one `npm install` to the next? Also, is there a better way to attach this to Backbone when I'm requiring it in via Browserify. I need the Browser based action to happen even though `typeof exports == "object"` will be true.

**Comment by anaumidis** [comment]
Same issue here...

**Comment by anaumidis** [comment]
Same issue here...

**Comment by wyuenho** [comment]
I'm not sure why you had a customized CommonJS block in the first place, looks like somebody had manually modified it after installation. Under a CJS environment, the canonical way to use Backbone.PageableCollection is to instantiate an instance. You can do `Backbone.Collection = Backbone.PageableCollection` as soon as all the libraries are loaded, supposedly in you "main" entry point.
