### ISSUE TITLE
How to handle with custom queryParams?

### ISSUE THREAD

**Issue by skotchio** [backbone-paginator/backbone.paginator#282]
Let's say I need to send any query params with GET request. How can I do it? Basically I'm looking for something like the following method `setQueryParams`. What is the best practices to make it?

**Comment by alxkolm** [comment]
collection.getFirstPage({foo: 'bar'})

**Comment by wyuenho** [comment]
All of the get* methods are basically wrappers around the `Collection.fetch` methods. Try `collection.getFirstPage({data: {foo: 'bar'}})`.
