### ISSUE TITLE
Running into "Uncaught RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by tkdan235** [backbone-paginator/backbone.paginator#283]
```
backbone.paginator.js:102 Uncaught RangeError: Maximum call stack size exceeded
```

I get this error when deleting multiple photos in our backbonejs web application.  Our app uses a restful api which requires me to delete photos one at a time.  After each photo is deleted the view is updated with that photo missing from the photo grid.  This view is paginated, so I am assuming pagination is being triggered on file deletion.  I am having a really hard time debugging the issue, was hoping to get some guidance here.  Any ideas?

All I have in chrome developer console:
![screen shot 2015-03-24 at 4 47 58 pm](https://cloud.githubusercontent.com/assets/3709575/6815325/987f1106-d245-11e4-90a5-d68714862d25.png)

**Comment by wyuenho** [comment]
Looks like an event loop here. Do you have a handler that removes the model after the server sent down the latest results?
