### ISSUE TITLE
Why is the latest version not on and CDN's?

### ISSUE THREAD

**Issue by chaimpeck** [backbone-paginator/backbone.paginator#289]
I would like to use backbone-paginator 2.0.2, but it is not on cdnjs.com or jsdelivr.com. The latest version on both CDN's is 0.8.

I am wondering why this lib is not on either CDN.

Thanks

**Comment by nrakochy** [comment]
+1  I just ran into this as well. 

When you update on cdnjs, you can configure the package.json to auto-update whenever new versions are released, so it should be relatively painless to maintain.

[Details and instructions](https://github.com/cdnjs/cdnjs) for cdnjs.

**Comment by sameercaresu** [comment]
+1

**Comment by wyuenho** [comment]
Feel free to make a PR to CDNJS. I've given up managing it, you should almost always bundle your own JS code instead of relying the CDN to load your libraries one at a time anyway. It doesn't actually help speed up your load time that much.
