### ISSUE TITLE
Possible to get the fullCollection in "server" mode?

### ISSUE THREAD

**Issue by geofflancaster** [backbone-paginator/backbone.paginator#290]
I'm trying to do a infinite scrolling div but I'd like to add the new page's models to the current collection without removing the old items. I've tried to pass the {remove: false} option into the getNextPage call but it doesn't change the result.

Anyone tried this before?

**Comment by jeanys** [comment]
Have you solved this issue yet?

**Comment by geofflancaster** [comment]
I'm not sure if this is what I did to get it working or if it was something else but I'm pretty sure it was the following:

I simply overrode the getNextPage function and added the following options.
```javascript
getNextPage: function (opts) {
      if (!opts) {
        opts = {
          silent: false
        };
      }
      opts.remove = false;
      return Backbone.PageableCollection.prototype.getNextPage.call(this, opts);
    }
```

**Comment by emileber** [comment]
I made an [infinite collection](https://gist.github.com/emileber/7c3b472fa45d8a208d9a8317bb2f38ae) inspired by the API of this lib. It is simple to use and you avoid fighting against the paging that backbone.paginator is providing.
