### ISSUE TITLE
Problem while using backbone-paginator with wiredep

### ISSUE THREAD

**Issue by Elaray** [backbone-paginator/backbone.paginator#291]
Hello, i've got problem while including paginator script into my project using wiredep. I've found out it's because of the absence of the bower.json file with 'main' field pointing to './lib/backbone.paginator.min.js', which is used by wiredep. Can this be fixed?

**Comment by HiroAgustin** [comment]
Had the same problem, ended up fixing it by adding the following to my `bower.json`:
```json
"overrides": {
  "backbone.paginator": {
    "main": "lib/backbone.paginator.js"
  }
}
```
I guess either bower is either not picking up package.json as a replacement for bower.json OR unlike npm it requires the `js` file extension in the main file.

**Comment by HiroAgustin** [comment]
Related #262

**Comment by wyuenho** [comment]
see bb3573d
