### ISSUE TITLE
[Feature Request] SOME sort of support for pre-filtering (or at least some guidelines on how to do it now)

### ISSUE THREAD

**Issue by ambischof** [backbone-paginator/backbone.paginator#294]
I'm aware of the issue https://github.com/backbone-paginator/backbone.paginator/issues/272 whose aim is to do in essence what I'm asking, but I decided to open an issue because I don't believe that's the *only* way of doing it.

I am also aware of this section in the faq: 
>Why doesn't backbone.paginator support filtering?
>
>Wheels should be reinvented only when they are crooked. backbone.paginator aims to do one thing only and does it well, which is pagination and sorting. Besides, since Backbone.PageableCollection is 100% compatible with Backbone.Collection, you can do filtering fairly easily with Backbone's built-in support for Underscore.js methods.

I feel this isn't the case because in almost all cases, you want filtering to happen *before* pagination. Filtering already paginated data is kind of useless. Any workaround I can think of now requires either 

* another wrapper collection holding unfiltered data and changing paginatorCollection.fullCollection to hold the filtered data (with a lot of update hooks) or 
* overriding the way the paginator collection accesses the fullCollection's models to include a hook to do the filtering.

I haven't actually tried either yet but I neither are particularly pretty.

Is there some solution that I'm missing?

**Comment by wyuenho** [comment]
In my mind, filtering is an exclusive View layer operation. You can either pick a number of interested models before pagination like you said, or you can pick the models you are interested to display from an unfiltered, paginated collection.

**Comment by ambischof** [comment]
I'm afraid I wholeheartedly disagree with that. It is a data operation and data operations are the responsibility of models and collections; views should be responsible for data. In my mind at least, the separation of views and models outweighs the separation of filtering and pagination. Speaking of which, filtering is no more a view operation than is pagination. I would say pagination is an even more view oriented operation than filtering, because paginations only purpose is to fit the data to the restrictions of the view.

Even if it was the responsibility of the view, filtering logically comes before pagination and views receive data that's already processed by the model or collection.

**Comment by amenadiel** [comment]
I'm using stronloop's loopback as my node backend, and it expects the query strings parameters to come in a certain way.

For this, I configured backbone paginator so it sends the limit and offset parameters as I need them. It was only logic to send the stringified where clause also.

This means that filtering manipulates the paginator state, and in turn that affects the query strings for the fetch action of the pageable collection

**Comment by ambischof** [comment]
For the project I wanted to use this for, it was operating client side, so that wasn't an option.

In the end, I used a virtual collection for filtering and did my own implementation of pagination, because I stubbornly refused to wrap my paginated collection in another virtual collection, since it's already made of two whole collections.

**Comment by wyuenho** [comment]
@ambischof PageableCollection views pagination as a complex plethora of CRUD synchronization operations between the pageable collection, the backing collection, ultimately server states. Filtering in general is an exclusively read-only operation. It is a view layer operation however you define "view". Wrapping a VirtualCollection in front of any collection in essence creates a "view" to the underlying collection. Fetching a page from PageableCollection makes PageableCollection a "view" layer to the server datastore. PageableCollection is an in-between layer that takes you one-step further beyond having only a list of models and no further. If you need mutilple layers of data views, VirtualCollection seems to be your best friend.
