### ISSUE TITLE
queryStringToParams converts empty strings to "true"

### ISSUE THREAD

**Issue by jamesodo** [backbone-paginator/backbone.paginator#298]
These lines
```js
var param = kvps[i];
kvp = param.split('='), k = kvp[0], v = kvp[1] || true;
k = decode(k), v = decode(v), ls = params[k];
if (_isArray(ls)) ls.push(v);
else if (ls) params[k] = [ls, v];
else params[k] = v;
```

(Link https://github.com/backbone-paginator/backbone.paginator/blob/master/lib/backbone.paginator.js#L84-L88 )

in queryStringToParams convert a query string like "a=&b=1" to the following object:

`{a: "true", b: 1}`

Why was `true` chosen as the default?
Should that check be more specific by comparing against `undefined` and `null`?

**Comment by wyuenho** [comment]
Well, when a key exists but a value doesn't, that usually means the key is a boolean. The returned value probably needs to be type-checked so decodeURIComponent doesn't convert the boolean to a string tho.
