### ISSUE TITLE
Pagination of single-loads of data with Backbone.history

### ISSUE THREAD

**Issue by kcijezie** [backbone-paginator/backbone.paginator#301]
First off Addy, your book, Developing Backbone Applications, is awesome!

With pagination of single-loads of data, is UI navigation (e.g form/page1, form/page2 ....) supported? Such that Backbone.history and Router.navigate can be used to trigger navigation too?

For my scenario, I have a form with 4 pages. Once the application starts, I want to paginate a single load of the form but be able to use the browsers back button to navigate backwards too.

Hope you can help.

**Comment by wyuenho** [comment]
You can listen to the `popstate` event on `window` in order to rerender your application's state when paging back and forth of your wizard. No backbone.paginator required.
