### ISSUE TITLE
Does not allow options.success callback.

### ISSUE THREAD

**Issue by miphe** [backbone-paginator/backbone.paginator#305]
In a PageableCollection, defining the `sync` method, if you define an `options.success` callback, which you may have been doing to your ajax fetch call before using Paginator, this will not allow for other methods be be called on success. Also, your collection will not be populated even though the call was successful.

_(mode `infinite`)_

```coffee
  parseRecords: (resp) ->
    console.log 'Parse!' # This will never run.
    resp.results

  sync: (method, model, options) ->
    options.type        = 'POST'
    options.contentType = API.getOption('post_content_type')
    options.dataType    = 'json'
    options.processData = false
    options.beforeSend  = (jqXHR, settings) ->
      settings.data     = JSON.stringify settings.data
    options.success     = (resp) ->
      console.log 'Success method, ajax succeded!'
```

The success callback, or complete callback, would sometimes a good place to cancel any ajax loaders etc.

However, if I omit the success callback, like below. Then the `parseRecords` method is invoked.

```coffee
  parseRecords: (resp) ->
    console.log 'Parse!' # This works!
    resp.results

  sync: (method, model, options) ->
    options.type        = 'POST'
    options.contentType = API.getOption('post_content_type')
    options.dataType    = 'json'
    options.processData = false
    options.beforeSend  = (jqXHR, settings) ->
      settings.data     = JSON.stringify settings.data
```

Is this intended, if so I feel it may need some exposure in the docs. Also, is there another callback I may use as `success` or `complete`?

**Comment by wyuenho** [comment]
https://github.com/backbone-paginator/backbone.paginator/blob/master/lib/backbone.paginator.js#L925

`sync` is already overridden by PageableCollection. If you overrides it again, just make sure you call the super again to have your own `success` function called.
