### ISSUE TITLE
fetch overwrites options.data with current state

### ISSUE THREAD

**Issue by dan-f** [backbone-paginator/backbone.paginator#308]
The current implementation of `fetch` allows the caller to pass in an `options.data` object which maps querystring parameter names to values to be sent to the server. This `options.data` is merged together with the collection's current state by examining the `state` and `queryParams` objects.

The problem is that `state`/`queryParams` currently take precedence. For example, if I run:

```javascript
collection.fetch({data: {page: 2});
```

The collection will still fetch the first page. This seems like a bug to me; I expected `options.data` to take precedence.

[Here is the problematic code](https://github.com/backbone-paginator/backbone.paginator/blob/master/lib/backbone.paginator.js#L1149-L1156):

```javascript
      var i, kvp, k, v, kvps = _pairs(queryParams), thisCopy = _clone(this);
      for (i = 0; i < kvps.length; i++) {
        kvp = kvps[i], k = kvp[0], v = kvp[1];
        v = _isFunction(v) ? v.call(thisCopy) : v;
        if (state[k] != null && v != null) {
          data[v] = state[k];
        }
      }
```

And a fix:

```javascript
      var i, kvp, k, v, kvps = _pairs(queryParams), thisCopy = _clone(this);
      for (i = 0; i < kvps.length; i++) {
        kvp = kvps[i], k = kvp[0], v = kvp[1];
        v = _isFunction(v) ? v.call(thisCopy) : v;
        if (state[k] != null && v != null && _.isUndefined(data[v])) {  // Only set if this key/val pair isn't already present in `data`.
          data[v] = state[k];
        }
      }
```

...And a more concise fix:

```javascript
      _.each(queryParams, function (v, k) {
        v = _isFunction(v) ? v.call(thisCopy) : v;
        if (state[k] != null && v != null && _.isUndefined(data[v])) {
          data[v] = state[k];
        }
      }, this);
```

**Comment by wyuenho** [comment]
This looks good. Please submit a PR along with a test. Thanks so much.
