### ISSUE TITLE
Client mode reset, page calculation incorrect.

### ISSUE THREAD

**Issue by bazineta** [backbone-paginator/backbone.paginator#309]
In the reset event handler, line 510, there's the following:
```
if (pageCol.mode == "client") {
  state.lastPage = state.currentPage = state.firstPage;
}
pageCol.state = pageCol._checkState(state);
```
Thus, on a reset, the state will be reset to the first page.  However, then, there's this:
```
pageCol.reset(fullCol.models.slice(pageStart, pageEnd),
  _extend({}, options, {parse: false}));
```
Which is still using the originally-calculated pageStart and pageEnd values, which will not be that of the page state that was just reset to the first page.  Thus, the state has changed such that it's now on the first page, but the pageCol was just reset with the old pageStart, and pageEnd values, not those of the first page.

The following change to the line 510 block seems to be the right thing to do:
```
 if (pageCol.mode == "client") {
  // Fix paged view not resetting to first page when the full collection is reset in client mode.
  firstPage = state.lastPage = state.currentPage = state.firstPage;
  currentPage = firstPage === 0 ? state.currentPage : state.currentPage - 1;
  pageStart = currentPage * pageSize;
  pageEnd = pageStart + pageSize;
}
```
Both the state and view will then be in sync.

**Comment by bazineta** [comment]
@wyuenho If you feel this to be a correct approach, I'd be happy to create a PR.  Just wanted to run it by you first.

**Comment by wyuenho** [comment]
@bazineta Please do and include a test for this. Apologizes for the delay.

**Comment by bazineta** [comment]
PR #310
