### ISSUE TITLE
Preflight request

### ISSUE THREAD

**Issue by costasapostolopoulos** [backbone-paginator/backbone.paginator#318]
Paginator stops working when there is a preflight request due to an Authorization header set in the sync. 
`No link found for page 2`

**Comment by TiagoEsterisco** [comment]
I am having the same issue. :/

**Comment by costasapostolopoulos** [comment]
@wyuenho Is this something you might take a look at?

**Comment by wyuenho** [comment]
Have you tried overriding the sync method?

**Comment by costasapostolopoulos** [comment]
Yes I tried that but none of the backbone.paginator functions work due to the first request. e.g. the parseLinks function never fires.

**Comment by wyuenho** [comment]
Closing this. CORS requests should be transparent. If your request failed, that probably means your Access-Allowed headers returned from the server is wrong and the browser stopped issuing the actual GET request after an OPTIONS.
