### ISSUE TITLE
Making 'url as function' more useful

### ISSUE THREAD

**Issue by saneef** [backbone-paginator/backbone.paginator#32]
In **Backbone.Collection** when the 'url' is used as function, we can bind the _this_ to the function and access the member variables while generating the url. This comes handy in many cases especially while following Rails URLs style like `http://example.com/product/show/1`

But in the case of backbone.paginator since the _url()_ is executed after `var queryOptions = _.clone(self.paginator_core);`, we cannot bind and access any of member variables of the collection. 

Is there a possibility to have `url: _.result(queryOptions, 'url')` run before the `paginator_core` is cloned? 

Or is there any hack to make the `server_api` variable to be part of the request URL like `<base_url>/$skip/4/$orderby/Releasedate`

**Comment by fra9001** [comment]
I suppose this was part of the old project. I wish I could do something like
```coffeescript

    class Stuff extends Backbone.PageableCollection
        url: '/stuff/:page'

by setting a function

    class Stuff extends Backbone.PageableCollection
        url: ->  "/stuff/#{@page}"

which would be immensely useful.
