### ISSUE TITLE
Constructor with parse option incompatible with non-Array models argument 

### ISSUE THREAD

**Issue by DriesVandermeulen** [backbone-paginator/backbone.paginator#337]
Hi there,

the constructor seems to be incompatible with the `{parse: true}` option and a non-Array `models` argument. For example, in my constructor I pass in an object like below.

``` javascript
const someData =  { 
    data: [ 
        { id: 1, name: 'han'}, 
        { id: 2, name: 'solo' }
    ],
    meta: {
        pagination: ... 
    }
}
const collection = new Backbone.PageableCollection(someData, { parse: true });
```

Normal Backbone.Collection behavior will run the models argument through the parse function of the collection before instantiating the models (if parse option is provided). Using Backbone.PageableCollection my collection gets populated with one model with two attributes `data` and `meta`.

The problem lies in the constructor on line `311`. 

``` javascript
if (!_isArray(models)) models = models ? [models] : [];
```

This will wrap the original `models` argument (in my case an object) in an array with all sorts of weirdness happening. I don't understand what the previous line needs to accomplish? If the `models` argument passed in the constructor is not an array, it makes no sense to just wrap it in an array.

I assume you wrap to make sure you can get the length on line `315`,

``` javascript
if (mode != "server" && state.totalRecords == null && !_isEmpty(models)) {
        state.totalRecords = models.length;
}
```

and avoid problems on line `312` & `343`.

``` javascript
models = models.slice();
```

``` javascript
models.splice.apply(models, [0, models.length].concat(this.models));
```

I like to make a pull request to resolve this issue. I have a hard time to wrap my head around all the slicing an dicing. Can you help me explain what line `312` & `343` are for?

**Comment by wyuenho** [comment]
311-312: Backbone.Collection can be passed an array of objects, 311-312 ensures the rest of the code will only be working on a shallow copy of the array passed in as opposed to triggering unwanted side effects inside the `switchMode` call chain.

Line 341 and 343 were a necessary hack at one time, but I forgot which version. I just tried commenting out 341 and 343 out and all tests passed with the backbone 1.3.3 Collection test suite. If removing the above 2 lines work with the 1.1.2 test suite, you can safely remove them in your PR.

**Comment by DriesVandermeulen** [comment]
Thx! I will try to work something out.
