### ISSUE TITLE
Disabling pagination with infinite mode

### ISSUE THREAD

**Issue by emileber** [backbone-paginator/backbone.paginator#344]
Is it possible to disable the pagination behavior?

I'm using this lib to do infinite scroll using the `fullCollection`, but when I add a new model at a position within the current page (like at index 0 when in the first page), the last model of that page (at index `pageSize-1`) is being removed from the collection (not the `fullCollection`) and a `remove` event is triggered on the model.

The model is removed at line [456](https://github.com/backbone-paginator/backbone.paginator/blob/d7ffe9187dacc4435b0cad80d87236c985faa9d2/lib/backbone.paginator.js#L456) and it's related to the [`pageStart`](https://github.com/backbone-paginator/backbone.paginator/blob/d7ffe9187dacc4435b0cad80d87236c985faa9d2/lib/backbone.paginator.js#L420) variable, or the whole pagination of that area.

I could just stop using the `remove` event for these models, but I would prefer to avoid that.

**Comment by emileber** [comment]
I think I found a way to achieve that.

I made the `pageSize` state a big number and I made my own state variable (`limit`) to replace the page size one inside the API fetch calls.

**Comment by wyuenho** [comment]
I'm not sure how to do infinite paging without paginating. Assuming you are able to add the model to the server at the exact same location, you are still effectively modifying the page size when you add a model to a page. The next time you fetch, you will have to fetch from the current offset + pageSize - 1, you will have to change the fetch method yourself to deal with this. Infinite paging mode is designed for read-only currently.

**Comment by emileber** [comment]
The API I'm working with uses a limit (page size) and an offset. My offset is just the `fullCollection` length. So I don't have any problems with fetching and saving.

The problem I am avoiding by making the `pageSize` a big number is that the page collection (which I don't really need) is being maintained in parallel with the `fullCollection`. 

But I'm willing to look into it and maybe propose a pull request if I can achieve what I want without changing the API.

**Comment by wyuenho** [comment]
The current page collection is always synced with the `fullCollection`. Are you using the `fullCollection` as the backing collection of your view? If that's the case, you won't need to attach any event listeners on the current page and you are free add and remove on the fullCollection anywhere you want. You'll still have to increment/decrement the limit and offset on your next fetch though, and you have to make sure the ordering is right on the server as well. It's tricky.

**Comment by emileber** [comment]
I'm not listening to the page collection, I want to use the `remove` event on the model itself, but since the page collection is synced, `remove` events are triggered on models by Backbone as a default behavior when removing a model from a collection.

So I use the `fullCollection` for everything, but without my hack, `remove` events are triggered on models and for me, it's like a false positive as they were not removed from the `fullCollection` but just the "virtual page", which I don't need. 

Hence my question about a possibility to disable the pagination behavior.

**Comment by emileber** [comment]
But thinking more about it, maybe I just don't need to use this lib, and I should just roll my own infinite-collection. I'll check what I can do and reply here with what I came up with.

**Comment by wyuenho** [comment]
Yep. Infinite paging is probably more straight forward with a custom backbone collection of you modify the collection.

**Comment by emileber** [comment]
I rolled my own "infinite collection".

I made a [public gist](https://gist.github.com/emileber/7c3b472fa45d8a208d9a8317bb2f38ae) to share it with the world. I've seen similar request through the issue of this lib, lots of people want to implement infinite scrolling and your lib provides lot of convenient features around this problem. 

My implementation is highly inspired by your API.
