### ISSUE TITLE
_contains is not a function in examples

### ISSUE THREAD

**Issue by ktarasov** [backbone-paginator/backbone.paginator#379]
Hi. I have the error when I start /examples/server-mode.html

> backbone.paginator.js:716 Uncaught TypeError: _contains is not a function
>    at child.switchMode (backbone.paginator.js:716)
>    at child.constructor (backbone.paginator.js:320)
>    at new child (backbone.js:1541)
>    at server-mode.html:81

**Comment by wyuenho** [comment]
Are you using underscore or lodash? If so, which version?

**Comment by ktarasov** [comment]
I did git clone your repository and opened examples/server-mode.html without any changes. See screenshot http://joxi.ru/Q2KelqoI9OdPNr

**Comment by ktarasov** [comment]
I found the cause. The problem related with incroorect version of underscore in examples.

**Comment by danlbob** [comment]
What's the correct Underscore version?

**Comment by ktarasov** [comment]
Correct version of underscore.js is 1.8.3
