### ISSUE TITLE
backbone.paginator v2.0.6

### ISSUE THREAD

**Issue by extend1994** [backbone-paginator/backbone.paginator#380]
Hi! I am a member from CDNJS and currently in charge of adding this lib according to https://github.com/cdnjs/cdnjs/issues/11545. Could you please release v2.0.6 in GitHub like the one on npm?
Thank you!

**Comment by extend1994** [comment]
Hello, any information?

**Comment by extend1994** [comment]
The files in backbone.paginator@2.0.6 on npm are the same as the the commit tree https://github.com/backbone-paginator/backbone.paginator/tree/d80ca918ef6ca79a022490dbea75b60cd1a5acc6. It's alright for cdnjs to add v2.0.6 manually.

**Comment by PeterDaveHello** [comment]
Hi @wyuenho, I think the v2.0.6 tag is missing in the repository, would you like to add it? Thanks.

**Comment by wyuenho** [comment]
Done

**Comment by PeterDaveHello** [comment]
Thanks @wyuenho
