### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by niksite** [backbone-paginator/backbone.paginator#386]
While trying demo url http://backbone-paginator.github.io/backbone.paginator/examples/server-mode.html I got the following error:

```
Uncaught TypeError: _contains is not a function
    at child.switchMode (backbone.paginator.js:714)
    at child.constructor (backbone.paginator.js:320)
    at new child (backbone.js:1541)
    at server-mode.html:81
```

**Comment by ogonkov** [comment]
Sorry for delay. Looks like the problem is gone (tested in Firefox 75, macOS). Feel free to reopen if you still have an issue.
